/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupIdTasksIndexRouteImport } from './routes/$groupId/tasks/index'
import { Route as GroupIdTasksTaskIdRouteImport } from './routes/$groupId/tasks/$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIdTasksIndexRoute = GroupIdTasksIndexRouteImport.update({
  id: '/$groupId/tasks/',
  path: '/$groupId/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIdTasksTaskIdRoute = GroupIdTasksTaskIdRouteImport.update({
  id: '/$groupId/tasks/$taskId',
  path: '/$groupId/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$groupId/tasks/$taskId': typeof GroupIdTasksTaskIdRoute
  '/$groupId/tasks/': typeof GroupIdTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$groupId/tasks/$taskId': typeof GroupIdTasksTaskIdRoute
  '/$groupId/tasks': typeof GroupIdTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$groupId/tasks/$taskId': typeof GroupIdTasksTaskIdRoute
  '/$groupId/tasks/': typeof GroupIdTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$groupId/tasks/$taskId' | '/$groupId/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$groupId/tasks/$taskId' | '/$groupId/tasks'
  id: '__root__' | '/' | '/$groupId/tasks/$taskId' | '/$groupId/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupIdTasksTaskIdRoute: typeof GroupIdTasksTaskIdRoute
  GroupIdTasksIndexRoute: typeof GroupIdTasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$groupId/tasks/': {
      id: '/$groupId/tasks/'
      path: '/$groupId/tasks'
      fullPath: '/$groupId/tasks/'
      preLoaderRoute: typeof GroupIdTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$groupId/tasks/$taskId': {
      id: '/$groupId/tasks/$taskId'
      path: '/$groupId/tasks/$taskId'
      fullPath: '/$groupId/tasks/$taskId'
      preLoaderRoute: typeof GroupIdTasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupIdTasksTaskIdRoute: GroupIdTasksTaskIdRoute,
  GroupIdTasksIndexRoute: GroupIdTasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
